// eslint-disable-next-line import/prefer-default-export
export const JODIT_TEXT_EDITOR_CONFIG = {
  addNewLine: false,
  readonly: false,
  placeholder: '',
  buttons: [
    'bold',
    'italic',
    'underline',
    '|',
    'paragraph',
    '|',
    'ul',
    'ol',
    '|',
    'link',
    'unlink',
    '|',
    'subscript',
    'superscript',
    '|',
    'file',
    'image',
    '|',
    'undo',
    'redo',
  ],
  buttonsMD: [
    'bold',
    'italic',
    'underline',
    '|',
    'paragraph',
    '|',
    'ul',
    'ol',
    '|',
    'link',
    'unlink',
    '|',
    'subscript',
    'superscript',
    '|',
    'file',
    'image',
    '|',
    'undo',
    'redo',
  ],
  buttonsSM: [
    'bold',
    'italic',
    'underline',
    '|',
    'paragraph',
    '|',
    'ul',
    'ol',
    '|',
    'link',
    'unlink',
    '|',
    'subscript',
    'superscript',
    '|',
    'file',
    'image',
    '|',
    'undo',
    'redo',
  ],
  buttonsXS: [
    'bold',
    'italic',
    'underline',
    '|',
    'paragraph',
    '|',
    'ul',
    'ol',
    '|',
    'link',
    'unlink',
    '|',
    'subscript',
    'superscript',
    '|',
    'file',
    'image',
    '|',
    'undo',
    'redo',
  ],
  events: {
    // eslint-disable-next-line no-shadow
    afterInit: (editor: any) => {
      const footer = editor.container.querySelector('.jodit-status-bar');
      if (footer) {
        footer.style.display = 'none'; // Hide the footer after initialization
      }
    },
  },
};
