export const DOSER_BATTERY_LOW = 3;

export const DOSER_CONDUCTIVITY_ABOVE_ALARM_LEVEL = 4;

export const CONDUCTIVITY_SPIKE_NOT_DETECTED = 12;

export const UNCLEARABLE_ALARM_LIST = [
  DOSER_BATTERY_LOW,
  DOSER_CONDUCTIVITY_ABOVE_ALARM_LEVEL,
  CONDUCTIVITY_SPIKE_NOT_DETECTED,
];
