import React from 'react';
import { CarbonAccountIcon } from '../assets/icons';
import { MenuItem } from '../types/common';
import {
  ACCESS_CUSTOMER,
  ACCESS_CUSTOMER_PROPERTY,
  ACCESS_DEVICE,
  ACCESS_HEALTH_CHECK,
  ACCESS_LAB_SAMPLE,
  ACCESS_LOG,
  ACCESS_UDOSE,
  ACCESS_UDOSE_MINI,
  ACCESS_USER,
  ACCESS_REPORT,
  ACCESS_ROLE,
  ACCESS_TAG,
  ACCESS_UDOSE_AG,
  ACCESS_REFERRER,
  ACCESS_PAYMENT,
  ACCESS_SALE,
  ACCESS_SUPPLEMENT,
  ACCESS_SUPPLEMENT_NUTRIENT,
  ACCESS_LAB_REPORT,
  ACCESS_PUBLISHED_LAB_REPORT,
  ACCESS_PADDOCK,
  ACCESS_CERES_TAG,
  ACCESS_CROP_LIFE_CYCLE,
  ACCESS_CROP,
  ACCESS_FERTILIZER,
  ACCESS_EMAIL_LOGS,
  ACCESS_NOTE,
  ACCESS_ALARM,
  ACCESS_CARBON_ACCOUNTING,
} from './permissions';

const MENU_ITEMS: MenuItem[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    isTitle: false,
    icon: 'bx bx-tachometer',
    permission: null,
    children: [
      {
        key: 'list-view',
        label: 'List View',
        url: '/dashboard',
        parentKey: 'dashboard',
        icon: 'bx bxs-circle',
        permission: null,
      },
      {
        key: 'map-view',
        label: 'Map View',
        url: '/dashboard-map-view',
        parentKey: 'dashboard',
        icon: 'bx bxs-circle',
        permission: null,
      },
    ],
  },
  {
    key: 'site-management',
    label: 'Site Management',
    isTitle: false,
    icon: 'bx bx-sitemap',
    permission: [
      ACCESS_DEVICE,
      ACCESS_UDOSE,
      ACCESS_UDOSE_MINI,
      ACCESS_UDOSE_AG,
    ],

    children: [
      {
        key: 'devices',
        label: 'Devices',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/devices/list',
        permission: ACCESS_DEVICE,
        parentKey: 'site-management',
      },
      {
        key: 'udose',
        label: 'uDoses',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/udose-sites/list',
        permission: ACCESS_UDOSE,
        parentKey: 'site-management',
      },
      {
        key: 'udose-mini',
        label: 'uDose Mini',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/sites/udose-mini/list',
        permission: ACCESS_UDOSE_MINI,
        parentKey: 'site-management',
      },
      {
        key: 'udose-ags',
        label: 'uDose Ags',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/udose-ags/list',
        permission: ACCESS_UDOSE_AG,
        parentKey: 'site-management',
      },
    ],
  },

  {
    key: 'entities',
    label: 'Entities',
    isTitle: false,
    icon: 'bx bx-building-house',
    children: [
      {
        key: 'customers',
        label: 'Customers',
        url: '/customers/list',
        parentKey: 'entities',
        icon: 'bx bxs-circle',
        permission: ACCESS_CUSTOMER,
      },
      {
        key: 'properties',
        label: 'Properties',
        url: '/properties/list',
        parentKey: 'entities',
        icon: 'bx bxs-circle',
        permission: ACCESS_CUSTOMER_PROPERTY,
      },
      {
        key: 'paddocks',
        label: 'Paddocks',
        url: '/paddocks/list',
        parentKey: 'entities',
        icon: 'bx bxs-circle',
        permission: ACCESS_PADDOCK,
      },
      {
        key: 'crops',
        label: 'Crops',
        url: '/crops/list',
        parentKey: 'entities',
        icon: 'bx bxs-circle',
        permission: ACCESS_CROP,
      },
      {
        key: 'crop-cycle',
        label: 'Crop Cycles',
        url: '/crop-cycles/list',
        parentKey: 'entities',
        icon: 'bx bxs-circle',
        permission: ACCESS_CROP_LIFE_CYCLE,
      },
    ],
    permission: [
      ACCESS_CUSTOMER,
      ACCESS_CUSTOMER_PROPERTY,
      ACCESS_PADDOCK,
      ACCESS_CROP,
      ACCESS_CROP_LIFE_CYCLE,
    ],
  },
  {
    key: 'lab',
    label: 'Lab',
    isTitle: false,
    icon: 'bx bxs-flask',
    url: '/lab-samples/list',
    children: [
      {
        key: 'lab-samples',
        label: 'Lab Samples',
        url: '/lab-samples/list',
        parentKey: 'lab',
        icon: 'bx bxs-circle',
        permission: ACCESS_LAB_SAMPLE,
      },
      {
        key: 'lab-reports',
        label: 'Lab Reports',
        url: '/lab-reports/list',
        parentKey: 'lab',
        icon: 'bx bxs-circle',
        permission: ACCESS_LAB_REPORT,
      },
      {
        key: 'lab-results',
        label: 'Lab Results',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/lab-results/list',
        parentKey: 'lab',
        permission: ACCESS_PUBLISHED_LAB_REPORT,
        badge: {
          variant: 'danger',
        },
      },
    ],
    permission: [
      ACCESS_LAB_SAMPLE,
      ACCESS_LAB_REPORT,
      ACCESS_PUBLISHED_LAB_REPORT,
    ],
  },

  // {
  //   key: 'ubot-sites',
  //   label: 'uBots',
  //   isTitle: false,
  //   icon: 'bx bx-cylinder',
  //   url: '/ubot-sites/list',
  //   permission: ACCESS_UBOT,
  // },

  {
    key: 'ceres-tags',
    label: 'Ceres Tags',
    isTitle: false,
    url: '/ceres-tags/list',
    icon: 'bx bx-purchase-tag-alt',
    permission: ACCESS_CERES_TAG,
  },

  // {
  //   key: 'trasnport-emissions',
  //   label: 'Transport Emissions',
  //   isTitle: false,
  //   icon: 'bx bxs-ship',
  //   url: '/transport-emissions/list',
  //   permission: ACCESS_TRANSPORT_EMISSION,
  // },

  // {
  //   key: 'map',
  //   label: 'Map',
  //   isTitle: false,
  //   icon: 'bx bx-map-alt',
  //   url: '/sites/map',
  //   permission: null,
  // },

  {
    key: 'nutrition-management',
    label: 'Nutrition Management',
    isTitle: false,
    icon: 'bx bx-droplet',
    url: '/supplements/list',
    permission: [
      ACCESS_SUPPLEMENT,
      ACCESS_SUPPLEMENT_NUTRIENT,
      ACCESS_FERTILIZER,
    ],
    children: [
      {
        key: 'nutrients',
        label: 'Nutrients',
        parentKey: 'nutrition-management',
        icon: 'bx bxs-circle',
        url: '/supplement-nutrients/list',
        permission: ACCESS_SUPPLEMENT_NUTRIENT,
      },
      {
        key: 'supplements',
        label: 'Supplements',
        url: '/supplements/list',
        parentKey: 'nutrition-management',
        icon: 'bx bxs-circle',
        permission: ACCESS_SUPPLEMENT,
      },

      {
        key: 'fertilizers',
        label: 'Fertilizers',
        url: '/fertilizers/list',
        parentKey: 'nutrition-management',
        icon: 'bx bxs-circle',
        permission: ACCESS_FERTILIZER,
      },
    ],
  },

  {
    key: 'utilities',
    label: 'Utilities',
    isTitle: false,
    icon: 'bx bx-notepad',
    permission: [
      ACCESS_TAG,
      ACCESS_HEALTH_CHECK,
      ACCESS_LOG,
      ACCESS_REPORT,
      ACCESS_EMAIL_LOGS,
      ACCESS_NOTE,
      ACCESS_ALARM,
    ],
    children: [
      {
        key: 'Tags',
        label: 'Tags',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/tags/list',
        parentKey: 'utilities',
        permission: ACCESS_TAG,
      },
      {
        key: 'health-checks',
        label: 'Health Checks',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/health-check/sites',
        parentKey: 'utilities',
        permission: ACCESS_HEALTH_CHECK,
      },
      {
        key: 'logs',
        label: 'Logs',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/logs',
        parentKey: 'utilities',
        permission: ACCESS_LOG,
      },
      {
        key: 'export-report',
        label: 'Export Report',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/export-report',
        parentKey: 'utilities',
        permission: ACCESS_REPORT,
      },
      {
        key: 'email-logs',
        label: 'Email Logs',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/email-logs',
        parentKey: 'utilities',
        permission: ACCESS_EMAIL_LOGS,
      },
      {
        key: 'notes',
        label: 'Notes',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/notes/list',
        parentKey: 'utilities',
        permission: ACCESS_NOTE,
      },
      {
        key: 'alarm',
        label: 'Alarm',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/alarm/list',
        parentKey: 'utilities',
        permission: ACCESS_ALARM,
      },
    ],
  },

  {
    key: 'carbon-accounting',
    label: 'Carbon Accounting',
    isTitle: false,
    url: '/carbon-accounting',
    permission: ACCESS_CARBON_ACCOUNTING,
    customIcon: <CarbonAccountIcon className="custom-icon text-primary" />,
  },

  // {
  //   key: 'News',
  //   label: 'News',
  //   isTitle: false,
  //   icon: 'bx bxs-news',
  //   url: '/news/list',
  //   permission: ACCESS_NEWS,
  // },

  {
    key: 'user-management',
    label: 'User Management',
    isTitle: false,
    icon: 'bx bx-user-circle',
    children: [
      {
        key: 'roles',
        label: 'Roles',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/roles/list',
        permission: ACCESS_ROLE,
        parentKey: 'user-management',
      },
      {
        key: 'users',
        label: 'Users',
        isTitle: false,
        icon: 'bx bxs-circle',
        url: '/users/list',
        permission: ACCESS_USER,
        parentKey: 'user-management',
      },
    ],
    permission: [ACCESS_ROLE, ACCESS_USER],
  },
  {
    key: 'referral-portal',
    label: 'Referral Portal',
    isTitle: false,
    icon: 'bx bx-user-voice',
    children: [
      {
        key: 'referrers',
        label: 'Referrers',
        url: '/referrers/list',
        parentKey: 'referral-portal',
        icon: 'bx bxs-circle',
        permission: ACCESS_REFERRER,
      },
      {
        key: 'sales',
        label: 'Sales',
        url: '/sales/list',
        parentKey: 'referral-portal',
        icon: 'bx bxs-circle',
        permission: ACCESS_SALE,
      },
      {
        key: 'payments',
        label: 'Payments',
        url: '/payments/list',
        parentKey: 'referral-portal',
        icon: 'bx bxs-circle',
        permission: ACCESS_PAYMENT,
      },
    ],
    permission: [ACCESS_REFERRER, ACCESS_PAYMENT, ACCESS_SALE],
  },
];

export default MENU_ITEMS;
