const UDOSE_AG_SESSION_STATUS_COMPLETED = 'Completed';
const UDOSE_AG_SESSION_STATUS_RUNNING = 'Running';
const UDOSE_AG_SESSION_STATUS_STARTED = 'Started';
const UDOSE_AG_SESSION_STATUS_ARMED = 'Armed';

export {
  UDOSE_AG_SESSION_STATUS_COMPLETED,
  UDOSE_AG_SESSION_STATUS_RUNNING,
  UDOSE_AG_SESSION_STATUS_STARTED,
  UDOSE_AG_SESSION_STATUS_ARMED,
};
