const AuthActionTypes: any = {
  API_RESPONSE_SUCCESS: '@@auth/API_RESPONSE_SUCCESS',
  API_RESPONSE_ERROR: '@@auth/API_RESPONSE_ERROR',

  LOGIN_USER: '@@auth/LOGIN_USER',
  LOGOUT_USER: '@@auth/LOGOUT_USER',
  SIGNUP_USER: '@@auth/SIGNUP_USER',
  FORGOT_PASSWORD: '@@auth/FORGOT_PASSWORD',
  FORGOT_PASSWORD_CHANGE: '@@auth/FORGOT_PASSWORD_CHANGE',

  RESET: '@@auth/RESET',

  VERIFY_OTP_START: '@@auth/VERIFY_OTP_START',
  VERIFY_OTP: '@@auth/VERIFY_OTP',

  UPDATE_PROFILE_PICTURE: '@@auth/UPDATE_PROFILE_PICTURE',

  REFRESH_PROFILE_PICTURE_URL: '@@auth/REFRESH_PROFILE_PICTURE_URL',

  CERESTAG_USER_LOGIN: '@@auth/CERESTAG_USER_LOGIN',
};

export default AuthActionTypes;
