const SiteActionTypes = {
  FETCH_SITES_START: '@@site/FETCH_SITES_START',
  FETCH_SITES_SUCCESS: '@@site/FETCH_SITES_SUCCESS',
  FETCH_SITES_ERROR: '@@site/FETCH_SITES_ERROR',

  FETCH_SITE_DETAIL_START: '@@site/FETCH_SITE_DETAIL_START',
  FETCH_SITE_DETAIL_SUCCESS: '@@site/FETCH_SITE_DETAIL_SUCCESS',
  FETCH_SITE_DETAIL_ERROR: '@@site/FETCH_SITE_DETAIL_ERROR',
};

export default SiteActionTypes;
