// @flow
import React, { useState } from 'react';
import { Row, Col, Card, Form, Button, InputGroup } from 'react-bootstrap';
import { useParams, useNavigate } from 'react-router-dom';
import classNames from 'classnames';

// components
import PageTitle from '../../components/PageTitle';

import { APICore } from '../../helpers/api/apiCore';
import { toast } from 'react-toastify';

const PasswordReset = () => {
  const api = new APICore();

  const { id } = useParams();
  let navigate = useNavigate();

  const [password, setPassword] = useState<string | undefined>(undefined);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);

  const [passwordType, setPasswordType] = useState('custom');
  const [isCopied, setIsCopied] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const copyPassword = (e: any) => {
    e.preventDefault();
    copyTextToClipboard(password)
      .then(() => {
        setIsCopied(true);
        setTimeout(function () {
          setIsCopied(false);
        }, 2000);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  async function copyTextToClipboard(text: string | undefined) {
    if ('clipboard' in navigator) {
      return await navigator.clipboard.writeText(text ? text : '');
    } else {
      return document.execCommand('copy', true, text);
    }
  }

  const generateNewPassword = () => {
    let password = Math.random().toString(20).substr(2, 8);
    setPassword(password);
    setIsAutoGenerated(true);
  };

  const handleChange = (e: any) => {
    reset();
    setPasswordType(e.target.value);
  };

  const reset = () => {
    setPassword(undefined);
    setIsAutoGenerated(false);
    setIsCopied(false);
    setShowPassword(false);
  };

  const handleSubmit = (e: any) => {
    e.preventDefault();
    api
      .create(`users/${id}/password/reset`, { password: password })
      .then((response) => {
        toast.success(
          'Password reset successfully. The new password will be sent to email shortly',
          { autoClose: 10000 }
        );
        navigate('/users/list');
      })
      .catch((error) => {
        toast.error("Couldn't reset password. Please try again!", {
          autoClose: 10000,
        });
      });
  };

  return (
    <>
      <PageTitle
        breadCrumbItems={[
          { label: 'Users', path: '/users/list' },
          { label: 'Reset Password', path: '', active: true },
        ]}
        title={'Reset Password'}
      />

      <Row className="justify-content-md-start">
        <Col md={6}>
          <Card className="">
            <Card.Body>
              <Col>
                <Form.Group className="mb-3">
                  <Form.Label className="form-label" htmlFor="exampleCheckbox">
                    Choose Password Type
                  </Form.Label>

                  <Form.Check
                    name="passwordType"
                    onChange={handleChange}
                    type="radio"
                    id="custom-password"
                    label="Custom Password"
                    value="custom"
                    checked={passwordType === 'custom'}
                  />

                  <Form.Check
                    name="passwordType"
                    onChange={handleChange}
                    type="radio"
                    id="auto-generated-password"
                    label="Auto Generated Password"
                    value="auto"
                    checked={passwordType === 'auto'}
                  />
                </Form.Group>
              </Col>
              {passwordType === 'custom' && (
                <Col>
                  <InputGroup className="mb-0">
                    <Form.Control
                      type={showPassword ? 'text' : 'password'}
                      placeholder="Enter Password"
                      name="password"
                      as="input"
                      onChange={(e) => setPassword(e.target.value)}
                      autoComplete="off"
                    />
                    <div
                      className={classNames(
                        'input-group-text',
                        'input-group-password',
                        {
                          'show-password': showPassword,
                        }
                      )}
                      data-password={showPassword ? 'true' : 'false'}>
                      <span
                        className="password-eye"
                        onClick={() => {
                          setShowPassword(!showPassword);
                        }}></span>
                    </div>
                  </InputGroup>
                </Col>
              )}

              {passwordType === 'auto' && (
                <Row>
                  <Col>
                    <Button
                      variant="secondary"
                      className="btn btn-secondary"
                      onClick={generateNewPassword}>
                      Generate random password
                    </Button>
                  </Col>

                  <Col>
                    {isAutoGenerated && (
                      <h4>
                        <span className="badge bg-light text-dark">
                          {' '}
                          {password} &nbsp;
                          <a href="" onClick={copyPassword}>
                            <i className="mdi mdi-content-copy"></i>{' '}
                          </a>
                        </span>
                        {isCopied && (
                          <i className="mdi mdi-check-circle-outline">Copied</i>
                        )}
                      </h4>
                    )}
                  </Col>
                </Row>
              )}
            </Card.Body>
            <Card.Footer>
              <Col>
                <Form.Group>
                  <Button
                    variant="secondary"
                    type="submit"
                    onClick={handleSubmit}
                    className=" btn btn-secondary">
                    Reset Password
                  </Button>
                </Form.Group>
              </Col>
            </Card.Footer>
          </Card>
        </Col>
      </Row>
    </>
  );
};

export default PasswordReset;
